controller_manager:
  ros__parameters:
    controller_list:
      - name: "joint_state_broadcaster"
        type: "joint_state_broadcaster/JointStateBroadcaster"
        hardware_interface: "hardware_interface::JointStateInterface"
      - name: "holonomic_velocity_controller"
        type: "ros2_control_demo_hardware/VelocityController"
        hardware_interface: "hardware_interface::VelocityJointInterface"
        joints:
          - "front_left_wheel_joint"
          - "front_right_wheel_joint"
          - "rear_left_wheel_joint"
          - "rear_right_wheel_joint"
        command_interface: "hardware_interface::VelocityJointInterface"
